project_name: timelinize
version: 2
builds:
  -
    id: "timelinize"
    binary: "timelinize"
    dir: .
    env:
      - CGO_ENABLED=1
    # I really wish goos and gooarch supported templating... our hack is to use sed on these
    goos:
      - _GOOS_
    goarch:
      - _GOARCH_
checksum:
  name_template: '{{ .Runtime.Goos }}-{{ .Runtime.Goarch }}-checksums.txt'
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
