project_name: timelinize
version: 2
builds:
  -
    id: "timelinize"
    binary: "timelinize"
    dir: .
    env:
      - CGO_ENABLED=1
    # We don't set goos and goarch because we invoke with --single-target to restrict build to current platform only
    goos:
      - _GOOS_
    goarch:
      - _GOARCH_
checksum:
  name_template: '{{ .Runtime.Goos }}-{{ .Runtime.Goarch }}-checksums.txt'
archives:
  -
    format_overrides:
      - goos: windows
        formats: zip
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
