name: lint
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    if: github.event.pull_request.draft == false
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true

      - uses: ./.github/actions/compile-libvips-linux
        if: runner.os == 'Linux'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
