name: lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install libraries (Linux)
        # install libheif (and dependency libde265) from an unofficial PPA which
        # is actually updated... Ubuntu's packages are too old, and strukturag's
        # doesn't exist for 24.04
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev
          sudo ldconfig

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # - name: downgrade heif
      #   run: |
      #     go get github.com/strukturag/libheif@v1.17.6
      #     go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
