name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install libraries (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: ./.github/actions/compile-libvips-linux

      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./...
