name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install libraries (Linux)
        if: runner.os == 'Linux'
        uses: ./.github/actions/compile-libvips-linux

      - name: Run tests
        run: go test ./...
